"""Read context reports produced by the Background Layer.

In Phase 1 there is no Background Layer yet, so the reports directory is
typically empty — that's fine. The Interactive Layer reads whatever is there
at session start and folds it into the system prompt.

Report files are plain markdown, one per domain (email-digest.md,
calendar.md, messages.md, ...). The filename minus extension is used as the
section header in the rendered context block.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class ContextReport:
    name: str  # filename stem, e.g. "email-digest"
    body: str  # markdown body


def load_reports(reports_dir: Path) -> list[ContextReport]:
    """Read all *.md files in `reports_dir`. Empty/missing dir returns []."""
    if not reports_dir.exists():
        return []

    reports: list[ContextReport] = []
    for path in sorted(reports_dir.glob("*.md")):
        try:
            body = path.read_text(encoding="utf-8").strip()
        except OSError as e:
            log.warning("Skipping unreadable context report %s: %s", path, e)
            continue
        if not body:
            continue
        reports.append(ContextReport(name=path.stem, body=body))
    return reports


def render_reports_block(reports: list[ContextReport]) -> str:
    """Render reports into a single markdown block for the system prompt.

    Returns "" when there are no reports — callers can concatenate without
    a guard.
    """
    if not reports:
        return ""
    parts = ["# Current context (auto-generated by background layer)"]
    for r in reports:
        parts.append(f"\n## {r.name}\n\n{r.body}")
    return "\n".join(parts)
