export const browserCoreExamples = [
  "juno browser status",
  "juno browser start",
  "juno browser stop",
  "juno browser tabs",
  "juno browser open https://example.com",
  "juno browser focus abcd1234",
  "juno browser close abcd1234",
  "juno browser screenshot",
  "juno browser screenshot --full-page",
  "juno browser screenshot --ref 12",
  "juno browser snapshot",
  "juno browser snapshot --format aria --limit 200",
  "juno browser snapshot --efficient",
  "juno browser snapshot --labels",
];

export const browserActionExamples = [
  "juno browser navigate https://example.com",
  "juno browser resize 1280 720",
  "juno browser click 12 --double",
  'juno browser type 23 "hello" --submit',
  "juno browser press Enter",
  "juno browser hover 44",
  "juno browser drag 10 11",
  "juno browser select 9 OptionA OptionB",
  "juno browser upload /tmp/juno/uploads/file.pdf",
  'juno browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "juno browser dialog --accept",
  'juno browser wait --text "Done"',
  "juno browser evaluate --fn '(el) => el.textContent' --ref 7",
  "juno browser console --level error",
  "juno browser pdf",
];
