"""Base interface every Background Layer job implements.

A job is a small, self-contained worker:
- It runs on a schedule.
- It produces a single markdown report file written into `reports_dir`.
- It optionally publishes interrupt events onto the EventBus when it
  detects something the user should be alerted to right away.

The runtime owns the scheduler registration and report write — jobs
just produce content.
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from server.config import JunoConfig
from server.inference import InferenceRouter
from server.scheduler import EventBus

log = logging.getLogger(__name__)


@dataclass
class JobContext:
    """Resources a job is given on every run.

    Stored on the job instance at registration; passed to `run()` so the
    callable signature stays simple.
    """

    config: JunoConfig
    reports_dir: Path
    inference: InferenceRouter
    bus: EventBus


@dataclass
class JobResult:
    """What `run()` returns. The runtime uses this to write the report."""

    report_filename: str  # e.g. "news.md"
    report_body: str  # full markdown content (no extra formatting added)


class BackgroundJob(ABC):
    """One scheduled background worker."""

    name: str  # short identifier; matches the config key

    def __init__(self, context: JobContext) -> None:
        self.context = context

    @abstractmethod
    async def run(self) -> JobResult:
        """Produce one report run."""

    # ---- helpers shared by all jobs -------------------------------------

    @staticmethod
    def now_iso() -> str:
        return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")

    def report_header(self, title: str) -> str:
        """Standard header every report carries. Lets the Interactive Layer
        and the human reader see provenance at a glance."""
        return (
            f"# {title}\n\n"
            f"_Generated by Juno background job `{self.name}` "
            f"at {self.now_iso()}._\n"
        )
